import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import type { Campaign } from '../api/analytics'
import { api, apiFailure } from '../api/client'
import { ConfirmButton, Field, Modal, StatusBadge } from '../components/Management'
import { useToast } from '../components/useToast'
import { formatBRL, formatCount } from '../lib/format'

function CampaignForm({ campaign, onClose }: { campaign: Campaign | null; onClose: () => void }) {
  const [name, setName] = useState(campaign?.name || ''), [channel, setChannel] = useState(campaign?.channel || ''), [externalId, setExternalId] = useState(campaign?.external_id || ''), [botId, setBotId] = useState(campaign?.bot_id || ''), [nicheId, setNicheId] = useState(campaign?.niche_id ? String(campaign.niche_id) : ''), [objective, setObjective] = useState(campaign?.objective || ''), [status, setStatus] = useState<'active' | 'paused' | 'completed'>((campaign?.status as 'active' | 'paused' | 'completed') || 'active'), [startedAt, setStartedAt] = useState(campaign?.started_at || ''), [endedAt, setEndedAt] = useState(campaign?.ended_at || '')
  const queryClient = useQueryClient(), { showToast } = useToast()
  const options = useQuery({ queryKey: ['campaign-options'], queryFn: async () => { const [bots, niches] = await Promise.all([api.GET('/api/bots', { params: { query: { page: 1, page_size: 200 } } }), api.GET('/api/niches')]); if (!bots.data || !niches.data) throw new Error('Falha ao carregar opções.'); return { bots: bots.data.items, niches: niches.data } } })
  const save = useMutation({ mutationFn: async () => { const body = { name, channel: channel || null, external_id: externalId || null, bot_id: botId || null, niche_id: nicheId ? Number(nicheId) : null, objective: objective || null, status, started_at: startedAt || null, ended_at: endedAt || null }; const result = campaign ? await api.PATCH('/api/campaigns/{campaign_id}', { params: { path: { campaign_id: campaign.id } }, body }) : await api.POST('/api/campaigns', { body }); if (!result.data) throw apiFailure(result.error, result.response) }, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['campaigns'] }); showToast('Campanha salva.', 'success'); onClose() }, onError: (error) => showToast(error instanceof Error ? error.message : 'Falha ao salvar.', 'error') })
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate() }
  return <Modal title={campaign ? 'Editar campanha' : 'Nova campanha'} onClose={onClose}><form className="form-grid columns" onSubmit={submit}><Field label="Nome" className="wide"><input required value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="Canal"><input value={channel} onChange={(e) => setChannel(e.target.value)} placeholder="meta_ads" /></Field><Field label="ID externo"><input value={externalId} onChange={(e) => setExternalId(e.target.value)} /></Field><Field label="Bot"><select value={botId} onChange={(e) => setBotId(e.target.value)}><option value="">Nenhum</option>{options.data?.bots.map((bot) => <option key={bot.id} value={bot.id}>{bot.name}</option>)}</select></Field><Field label="Nicho"><select value={nicheId} onChange={(e) => setNicheId(e.target.value)}><option value="">Nenhum</option>{options.data?.niches.map((niche) => <option key={niche.id} value={niche.id}>{niche.name}</option>)}</select></Field><Field label="Objetivo"><select value={objective} onChange={(e) => setObjective(e.target.value)}><option value="">Não definido</option><option value="group_join">Entrada em grupo</option><option value="sales">Vendas</option></select></Field><Field label="Status"><select value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="active">Ativa</option><option value="paused">Pausada</option><option value="completed">Concluída</option></select></Field><Field label="Início"><input type="date" value={startedAt} onChange={(e) => setStartedAt(e.target.value)} /></Field><Field label="Fim"><input type="date" value={endedAt} onChange={(e) => setEndedAt(e.target.value)} /></Field><div className="form-actions wide"><button type="button" className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary" disabled={save.isPending}>Salvar</button></div></form></Modal>
}

function CampaignMetrics({ campaign }: { campaign: Campaign }) {
  const query = useQuery({ queryKey: ['campaign-metrics', campaign.id], queryFn: async () => { const result = await api.GET('/api/campaigns/{campaign_id}/metrics', { params: { path: { campaign_id: campaign.id } } }); if (!result.data) throw apiFailure(result.error, result.response); return result.data }, refetchInterval: 30_000 })
  return <div className="campaign-metrics"><span><small>Gasto</small><strong>{formatBRL(query.data?.spend)}</strong></span><span><small>Entradas</small><strong>{formatCount(query.data?.group_joins)}</strong></span><span><small>Custo por entrada</small><strong>{formatBRL(query.data?.cost_per_join)}</strong></span></div>
}

export function Campaigns() {
  const [editing, setEditing] = useState<Campaign | null | undefined>(undefined), { showToast } = useToast(), queryClient = useQueryClient()
  const campaigns = useQuery({ queryKey: ['campaigns'], queryFn: async () => { const result = await api.GET('/api/campaigns', { params: { query: { page: 1, page_size: 200 } } }); if (!result.data) throw apiFailure(result.error, result.response); return result.data.items }, refetchInterval: 30_000 })
  const remove = useMutation({ mutationFn: async (campaign: Campaign) => { const result = await api.DELETE('/api/campaigns/{campaign_id}', { params: { path: { campaign_id: campaign.id } } }); if (result.response.status !== 204) throw apiFailure(result.error, result.response) }, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['campaigns'] }); showToast('Campanha excluída.', 'success') } })
  return <section><div className="page-heading"><div><p className="eyebrow">AQUISIÇÃO</p><h1>Campanhas</h1><p>Compare gasto, entradas em grupo e custo de aquisição.</p></div><button className="button primary" onClick={() => setEditing(null)}>Nova campanha</button></div><div className="card-list">{campaigns.data?.map((campaign) => <article className="management-card" key={campaign.id}><div className="card-title"><div><h3>{campaign.name}</h3><small>{campaign.channel || 'Canal não informado'}</small></div><StatusBadge value={campaign.status} /></div><CampaignMetrics campaign={campaign} /><div className="card-actions"><button className="button ghost" onClick={() => setEditing(campaign)}>Editar</button><ConfirmButton question={`Excluir ${campaign.name}?`} onConfirm={() => remove.mutate(campaign)}>Excluir</ConfirmButton></div></article>)}</div>{editing !== undefined && <CampaignForm campaign={editing} onClose={() => setEditing(undefined)} />}</section>
}
