import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { Expense } from '../api/analytics'
import { api, ApiError, apiFailure } from '../api/client'
import { ConfirmButton, Field, Modal } from '../components/Management'
import { useToast } from '../components/useToast'
import { formatBRL, formatDate } from '../lib/format'
import { addDecimalStrings, normalizeMoneyInput } from '../lib/moneyInput'

function ExpenseForm({ expense, onClose }: { expense: Expense | null; onClose: () => void }) {
  const [description, setDescription] = useState(expense?.description || ''), [amount, setAmount] = useState(expense?.amount.replace('.', ',') || ''), [date, setDate] = useState(expense?.incurred_on || ''), [category, setCategory] = useState(expense?.category_id ? String(expense.category_id) : ''), [platform, setPlatform] = useState(expense?.platform_id ? String(expense.platform_id) : ''), [campaign, setCampaign] = useState(expense?.campaign_id || ''), [bot, setBot] = useState(expense?.bot_id || ''), [niche, setNiche] = useState(expense?.niche_id ? String(expense.niche_id) : ''), [notes, setNotes] = useState(expense?.notes || ''), [amountError, setAmountError] = useState('')
  const queryClient = useQueryClient(), { showToast } = useToast()
  const options = useQuery({ queryKey: ['expense-options'], queryFn: async () => { const [categories, platforms, campaigns, bots, niches] = await Promise.all([api.GET('/api/expense-categories'), api.GET('/api/platforms'), api.GET('/api/campaigns', { params: { query: { page: 1, page_size: 200 } } }), api.GET('/api/bots', { params: { query: { page: 1, page_size: 200 } } }), api.GET('/api/niches')]); if (!categories.data || !platforms.data || !campaigns.data || !bots.data || !niches.data) throw new Error('Falha ao carregar opções.'); return { categories: categories.data, platforms: platforms.data, campaigns: campaigns.data.items, bots: bots.data.items, niches: niches.data } } })
  const save = useMutation({ mutationFn: async (value: string) => { const body = { description, amount: value, incurred_on: date, currency: 'BRL', category_id: category ? Number(category) : null, platform_id: platform ? Number(platform) : null, campaign_id: campaign || null, bot_id: bot || null, niche_id: niche ? Number(niche) : null, notes: notes || null }; const result = expense ? await api.PATCH('/api/expenses/{expense_id}', { params: { path: { expense_id: expense.id } }, body }) : await api.POST('/api/expenses', { body }); if (!result.data) throw apiFailure(result.error, result.response) }, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['expenses'] }); showToast('Despesa salva.', 'success'); onClose() }, onError: (error) => showToast(error instanceof Error ? error.message : 'Falha ao salvar.', 'error') })
  const submit = (event: FormEvent) => { event.preventDefault(); const parsed = normalizeMoneyInput(amount); if (!parsed.value) return setAmountError(parsed.error || 'Valor inválido.'); setAmountError(''); save.mutate(parsed.value) }
  const select = (label: string, value: string, setter: (value: string) => void, items: ReadonlyArray<{ id: string | number; name?: string | null; label?: string }>) => <Field label={label}><select value={value} onChange={(event) => setter(event.target.value)}><option value="">Nenhum</option>{items.map((item) => <option value={item.id} key={item.id}>{item.name || item.label || item.id}</option>)}</select></Field>
  return <Modal title={expense ? 'Editar despesa' : 'Nova despesa'} onClose={onClose}><form className="form-grid columns" onSubmit={submit}><Field label="Descrição" className="wide"><input required value={description} onChange={(e) => setDescription(e.target.value)} /></Field><Field label="Valor" error={amountError}><input required inputMode="decimal" placeholder="1.234,56" value={amount} onChange={(e) => setAmount(e.target.value)} /></Field><Field label="Data"><input required type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field>{select('Categoria', category, setCategory, options.data?.categories || [])}{select('Plataforma', platform, setPlatform, options.data?.platforms || [])}{select('Campanha', campaign, setCampaign, options.data?.campaigns || [])}{select('Bot', bot, setBot, options.data?.bots || [])}{select('Nicho', niche, setNiche, options.data?.niches || [])}<Field label="Observações" className="wide"><textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></Field><div className="form-actions wide"><button type="button" className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary" disabled={save.isPending}>Salvar</button></div></form></Modal>
}

export function Expenses() {
  const [editing, setEditing] = useState<Expense | null | undefined>(undefined), [from, setFrom] = useState(''), [to, setTo] = useState(''), [file, setFile] = useState<File | null>(null), [result, setResult] = useState<{ imported: number; skipped: number; errors: { line: number; message: string }[] } | null>(null)
  const queryClient = useQueryClient(), { showToast } = useToast()
  const expenses = useQuery({ queryKey: ['expenses', from, to], queryFn: async () => { const response = await api.GET('/api/expenses', { params: { query: { page: 1, page_size: 200, sort: '-incurred_on', ...(from ? { from } : {}), ...(to ? { to } : {}) } } }); if (!response.data) throw apiFailure(response.error, response.response); return response.data }, refetchInterval: 30_000 })
  const categories = useQuery({ queryKey: ['expense-categories'], queryFn: async () => { const response = await api.GET('/api/expense-categories'); if (!response.data) throw apiFailure(response.error, response.response); return response.data } })
  const remove = useMutation({ mutationFn: async (expense: Expense) => { const response = await api.DELETE('/api/expenses/{expense_id}', { params: { path: { expense_id: expense.id } } }); if (response.response.status !== 204) throw apiFailure(response.error, response.response) }, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['expenses'] }); showToast('Despesa excluída.', 'success') } })
  const importer = useMutation({ mutationFn: async (csv: File) => { const response = await api.POST('/api/expenses/import', { body: { file: '' }, bodySerializer: () => { const data = new FormData(); data.append('file', csv); return data } }); if (!response.data) throw apiFailure(response.error, response.response); return response.data }, onSuccess: async (data) => { setResult(data); await queryClient.invalidateQueries({ queryKey: ['expenses'] }) }, onError: (error) => { if (error instanceof ApiError && Object.keys(error.fields).length) { setResult({ imported: 0, skipped: 0, errors: Object.entries(error.fields).map(([key, message]) => ({ line: Number(key.replace('line_', '')) || 0, message })) }); return } showToast(error instanceof Error ? error.message : 'Falha ao importar.', 'error') } })
  const sums = new Map<number, { raw: string; value: number }>()
  expenses.data?.items.forEach((expense) => { const current = sums.get(expense.category_id || -1); const raw = current ? addDecimalStrings(current.raw, expense.amount) : expense.amount; sums.set(expense.category_id || -1, { raw, value: Number(raw) }) })
  const chart = [...sums].map(([id, value]) => ({ name: categories.data?.find((item) => item.id === id)?.name || 'Sem categoria', value: value.value, raw: value.raw }))
  return <section><div className="page-heading"><div><p className="eyebrow">INVESTIMENTO</p><h1>Despesas</h1><p>Entenda para onde o dinheiro vai e mantenha o custo real atualizado.</p></div><button className="button primary" onClick={() => setEditing(null)}>Nova despesa</button></div><section className="panel"><div className="filter-selects"><label className="filter-field"><span>De</span><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label className="filter-field"><span>Até</span><input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label></div></section><section className="panel"><h2>Gastos por categoria</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height={280}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" opacity={0.25} /><XAxis dataKey="name" /><YAxis /><Tooltip formatter={(_value, _name, item) => formatBRL(item.payload.raw)} /><Bar dataKey="value" fill="#2f8b5b" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="panel"><h2>Importar CSV</h2><div className="inline-form"><input aria-label="CSV de despesas" type="file" accept=".csv,text/csv" onChange={(e) => setFile(e.target.files?.[0] || null)} /><button className="button ghost" disabled={!file || importer.isPending} onClick={() => file && importer.mutate(file)}>Importar</button></div>{result && <><p><strong>{result.imported}</strong> importadas · <strong>{result.skipped}</strong> ignoradas</p>{result.errors.length > 0 && <div className="inline-error" role="alert"><strong>Arquivo recusado: nenhuma linha foi importada.</strong><ul>{result.errors.map((error) => <li key={`${error.line}-${error.message}`}>Linha {error.line}: {error.message}</li>)}</ul></div>}</>}</section><div className="responsive-table"><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Valor</th><th>Origem</th><th>Ações</th></tr></thead><tbody>{expenses.data?.items.map((expense) => <tr key={expense.id}><td data-label="Data">{formatDate(`${expense.incurred_on}T12:00:00Z`)}</td><td data-label="Descrição">{expense.description}<small>{expense.notes}</small></td><td data-label="Categoria">{categories.data?.find((item) => item.id === expense.category_id)?.name || 'Sem categoria'}</td><td data-label="Valor">{formatBRL(expense.amount)}</td><td data-label="Origem">{expense.source}</td><td data-label="Ações"><div className="table-actions"><button className="button ghost" onClick={() => setEditing(expense)}>Editar</button><ConfirmButton question={`Excluir ${expense.description}?`} onConfirm={() => remove.mutate(expense)}>Excluir</ConfirmButton></div></td></tr>)}</tbody></table></div>{editing !== undefined && <ExpenseForm expense={editing} onClose={() => setEditing(undefined)} />}</section>
}
