import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { api, apiFailure } from '../api/client'
import { StatusBadge } from '../components/Management'
import { formatDate } from '../lib/format'

export function Logs() {
  const [page, setPage] = useState(1), [level, setLevel] = useState(''), [type, setType] = useState(''), [botId, setBotId] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState('')
  const bots = useQuery({ queryKey: ['log-bots'], queryFn: async () => { const result = await api.GET('/api/bots', { params: { query: { page: 1, page_size: 200 } } }); if (!result.data) throw apiFailure(result.error, result.response); return result.data.items } })
  const events = useQuery({ queryKey: ['events', page, level, type, botId, from, to], queryFn: async () => { const result = await api.GET('/api/events', { params: { query: { page, page_size: 25, ...(level ? { level: level as 'info' | 'warning' | 'error' | 'critical' } : {}), ...(type ? { type } : {}), ...(botId ? { bot_id: botId } : {}), ...(from ? { from } : {}), ...(to ? { to } : {}) } } }); if (!result.data) throw apiFailure(result.error, result.response); return result.data }, refetchInterval: 30_000 })
  const resetPage = (setter: (value: string) => void, value: string) => { setter(value); setPage(1) }
  return <section className="technical-page"><div className="page-heading"><div><p className="eyebrow">ÁREA TÉCNICA</p><h1>Logs técnicos</h1><p>Diagnóstico detalhado para investigação; alertas ficam na área operacional.</p></div></div><section className="panel"><div className="filter-selects"><label className="filter-field"><span>Nível</span><select value={level} onChange={(e) => resetPage(setLevel, e.target.value)}><option value="">Todos</option><option>info</option><option>warning</option><option>error</option><option>critical</option></select></label><label className="filter-field"><span>Tipo</span><input value={type} onChange={(e) => resetPage(setType, e.target.value)} /></label><label className="filter-field"><span>Bot</span><select value={botId} onChange={(e) => resetPage(setBotId, e.target.value)}><option value="">Todos</option>{bots.data?.map((bot) => <option value={bot.id} key={bot.id}>{bot.name}</option>)}</select></label><label className="filter-field"><span>De</span><input type="date" value={from} onChange={(e) => resetPage(setFrom, e.target.value)} /></label><label className="filter-field"><span>Até</span><input type="date" value={to} onChange={(e) => resetPage(setTo, e.target.value)} /></label></div></section><div className="event-list">{events.data?.items.map((event) => <article className="event-card" key={event.id}><header><StatusBadge value={event.level} /><strong>{event.type}</strong><time>{formatDate(event.created_at)}</time></header><p>{event.message}</p>{event.detail && <details><summary>Ver detalhe JSON</summary><pre>{JSON.stringify(event.detail, null, 2)}</pre></details>}</article>)}</div><div className="pagination"><button className="button ghost" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Anterior</button><span>Página {page}</span><button className="button ghost" disabled={!events.data || page * events.data.page_size >= events.data.total} onClick={() => setPage((value) => value + 1)}>Próxima</button></div></section>
}
