import { useQuery } from '@tanstack/react-query'
import { SlidersHorizontal, X } from 'lucide-react'
import { useState } from 'react'
import { api, apiFailure } from '../api/client'
import { presetDates, type Preset } from '../lib/metricFilters'
import { useMetricFilters } from './useMetricFilters'
const filterKeys = ['platform_id', 'account_id', 'bot_id', 'niche_id', 'group_id', 'campaign_id', 'phone_id'] as const
const labels: Record<typeof filterKeys[number], string> = { platform_id: 'Plataforma', account_id: 'Conta', bot_id: 'Bot', niche_id: 'Nicho', group_id: 'Grupo', campaign_id: 'Campanha', phone_id: 'Telefone' }
function useOptions() { return useQuery({ queryKey: ['global-filter-options'], queryFn: async () => { const [platforms, accounts, bots, niches, groups, campaigns, phones] = await Promise.all([api.GET('/api/platforms'), api.GET('/api/accounts', { params: { query: { page: 1, page_size: 200 } } }), api.GET('/api/bots', { params: { query: { page: 1, page_size: 200 } } }), api.GET('/api/niches'), api.GET('/api/groups', { params: { query: { page: 1, page_size: 200 } } }), api.GET('/api/campaigns', { params: { query: { page: 1, page_size: 200 } } }), api.GET('/api/phones', { params: { query: { page: 1, page_size: 200 } } })]); for (const result of [platforms, accounts, bots, niches, groups, campaigns, phones]) if (!result.data) throw apiFailure(result.error, result.response); return { platforms: platforms.data!, accounts: accounts.data!.items, bots: bots.data!.items, niches: niches.data!, groups: groups.data!.items, campaigns: campaigns.data!.items, phones: phones.data!.items } }, staleTime: 60_000 }) }
export function GlobalFilters() {
  const { filters, params, update } = useMetricFilters(), options = useOptions(), [open, setOpen] = useState(false), preset = (params.get('preset') || '30d') as Preset
  const setPreset = (value: Preset) => { if (value === 'custom') return update({ preset: value }); const dates = presetDates(value); update({ preset: value, from: dates.from, to: dates.to }) }
  const data = options.data, collections = data ? { platform_id: data.platforms, account_id: data.accounts, bot_id: data.bots, niche_id: data.niches, group_id: data.groups, campaign_id: data.campaigns, phone_id: data.phones } : null
  const active = filterKeys.filter((key) => params.has(key))
  const select = (key: typeof filterKeys[number]) => { const items = collections?.[key] ?? []; return <label className="filter-field" key={key}><span>{labels[key]}</span><select aria-label={labels[key]} value={params.get(key) || ''} onChange={(event) => update({ [key]: event.target.value || undefined })}><option value="">Todos</option>{items.map((item) => <option key={item.id} value={item.id}>{('name' in item && item.name) || ('label' in item && item.label) || item.id}</option>)}</select></label> }
  const selectedName = (key: typeof filterKeys[number]) => { const value = params.get(key); const item = collections?.[key].find((entry) => String(entry.id) === value); return item && (('name' in item && item.name) || ('label' in item && item.label)) || value }
  return <section className="global-filters" aria-label="Filtros globais"><div className="filter-bar"><div className="filter-presets" role="group" aria-label="Período">{([['today', 'Hoje'], ['7d', '7 dias'], ['30d', '30 dias'], ['month', 'Este mês'], ['previous_month', 'Mês anterior'], ['custom', 'Personalizado']] as const).map(([value, label]) => <button type="button" aria-pressed={preset === value} className={preset === value ? 'active' : ''} key={value} onClick={() => setPreset(value)}>{label}</button>)}</div>{preset === 'custom' && <div className="custom-dates"><label className="filter-field"><span>De</span><input aria-label="De" type="date" value={filters.from} onChange={(event) => update({ from: event.target.value })} /></label><label className="filter-field"><span>Até</span><input aria-label="Até" type="date" value={filters.to} onChange={(event) => update({ to: event.target.value })} /></label></div>}<button className="button ghost filter-toggle" type="button" aria-expanded={open} onClick={() => setOpen((value) => !value)}><SlidersHorizontal />Filtros{active.length > 0 && <span className="count">{active.length}</span>}</button></div>{data && <div className="filter-drawer" hidden={!open}>{filterKeys.map(select)}</div>}{active.length > 0 && <div className="filter-chips">{active.map((key) => <button type="button" key={key} onClick={() => update({ [key]: undefined })}>{labels[key]}: {selectedName(key)}<X /></button>)}<button className="clear-filters" type="button" onClick={() => update(Object.fromEntries(filterKeys.map((key) => [key, undefined])))}>Limpar filtros</button></div>}</section>
}
