import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { api, apiFailure } from '../api/client'
import { errorMessage, type Bot, type Phone } from '../api/management'
import { ConfirmButton, Field, Modal } from './Management'
import { useToast } from './useToast'
import { allBots, allGroups, allAccounts, allPhones } from '../api/testBots'
import { configDifferences } from '../lib/configDifferences'

export function ConfigDifferences({ current, next }: { current: Bot; next: Bot }) {
  const differences = configDifferences(current, next)
  return <div>{differences.length ? <ul>{differences.map((diff) => <li key={diff.path}><strong>{diff.path}</strong>: {JSON.stringify(diff.before) ?? '—'} → {JSON.stringify(diff.after) ?? '—'}</li>)}</ul> : <p>Nenhuma diferença de configuração.</p>}</div>
}

export function CreateTestBot({ phones, onClose }: { phones: Phone[]; onClose: () => void }) {
  const navigate = useNavigate(), queryClient = useQueryClient(), { showToast } = useToast()
  const bots = useQuery({ queryKey: ['bots', 'all'], queryFn: allBots })
  const groups = useQuery({ queryKey: ['groups', 'test-create'], queryFn: allGroups })
  const accounts = useQuery({ queryKey: ['accounts', 'test-create'], queryFn: allAccounts })
  const allPhoneOptions = useQuery({ queryKey: ['phones', 'all'], queryFn: allPhones })
  const [name, setName] = useState(''), [sourceId, setSourceId] = useState(''), [phoneId, setPhoneId] = useState('')
  const [groupIds, setGroupIds] = useState<string[]>([]), [accountIds, setAccountIds] = useState<string[]>([])
  const production = (bots.data ?? []).filter((bot) => !bot.is_test)
  const warning = production.some((bot) => bot.status === 'active' && ((phoneId && bot.phone_id === phoneId) || bot.group_ids.some((id) => groupIds.includes(id))))
  const create = useMutation({ mutationFn: async () => { const result = await api.POST('/api/bots/test', { body: { name, source_bot_id: sourceId || null, phone_id: phoneId || null, group_ids: groupIds, account_ids: accountIds } }); if (!result.data) throw apiFailure(result.error, result.response); return result.data }, onSuccess: async (bot) => { await queryClient.invalidateQueries({ queryKey: ['bots'] }); showToast('Bot de teste criado pausado.', 'success'); navigate(`/bots/${bot.id}`) }, onError: (error) => showToast(errorMessage(error), 'error') })
  return <Modal title="Novo bot de teste" onClose={onClose}><form className="form-grid" onSubmit={(event) => { event.preventDefault(); create.mutate() }}><Field label="Nome"><input required maxLength={200} value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Começar a partir de"><select value={sourceId} onChange={(event) => { setSourceId(event.target.value); setAccountIds(production.find((bot) => bot.id === event.target.value)?.account_ids ?? []) }}><option value="">Configuração padrão</option>{production.map((bot) => <option key={bot.id} value={bot.id}>{bot.name}</option>)}</select></Field><Field label="Telefone"><select value={phoneId} onChange={(event) => { setPhoneId(event.target.value); setGroupIds([]) }}><option value="">Sem telefone</option>{(allPhoneOptions.data ?? phones).map((phone) => <option key={phone.id} value={phone.id}>{phone.label} · {phone.number}</option>)}</select></Field><fieldset><legend>Grupos do telefone</legend>{(groups.data ?? []).filter((group) => group.phone_id === phoneId && group.status !== 'archived').map((group) => <label className="check" key={group.id}><input type="checkbox" checked={groupIds.includes(group.id)} onChange={(event) => setGroupIds(event.target.checked ? [...groupIds, group.id] : groupIds.filter((id) => id !== group.id))} />{group.name ?? group.whatsapp_id}</label>)}</fieldset><fieldset><legend>Contas</legend>{(accounts.data ?? []).map((account) => <label className="check" key={account.id}><input type="checkbox" checked={accountIds.includes(account.id)} onChange={(event) => setAccountIds(event.target.checked ? [...accountIds, account.id] : accountIds.filter((id) => id !== account.id))} />{account.label}</label>)}</fieldset>{[bots, groups, accounts, allPhoneOptions].some((query) => query.isError) && <p role="alert">Não foi possível carregar as opções. Reabra o formulário para tentar novamente.</p>}{warning && <p role="alert">Este grupo/telefone é de produção: as mensagens do teste chegam a pessoas reais.</p>}<div className="form-actions"><button type="button" className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary" disabled={create.isPending || [bots, groups, accounts, allPhoneOptions].some((query) => query.isLoading || query.isError)}>Criar bot de teste</button></div></form></Modal>
}

export function TestBotConfig({ bot, isAdmin }: { bot: Bot; isAdmin: boolean }) {
  const navigate = useNavigate(), queryClient = useQueryClient(), { showToast } = useToast()
  const [importing, setImporting] = useState(false), [targetId, setTargetId] = useState(bot.test_source_bot_id ?? ''), [confirmed, setConfirmed] = useState(false)
  const targets = useQuery({ queryKey: ['bots', 'all'], queryFn: allBots, enabled: bot.is_test })
  const [backupPage, setBackupPage] = useState(1)
  const backups = useQuery({ queryKey: ['config-backups', bot.id, backupPage], queryFn: async () => { const result = await api.GET('/api/bots/{bot_id}/config-backups', { params: { path: { bot_id: bot.id }, query: { page: backupPage, page_size: 20 } } }); if (!result.data) throw apiFailure(result.error, result.response); return result.data }, enabled: !bot.is_test })
  const update = useMutation({ mutationFn: async ({ operation, backupId }: { operation: 'import' | 'archive' | 'restore'; backupId?: string }) => {
    const result = operation === 'import' ? await api.POST('/api/bots/{test_bot_id}/import-config', { params: { path: { test_bot_id: bot.id } }, body: { target_bot_id: targetId } }) : operation === 'archive' ? await api.POST('/api/bots/{bot_id}/archive', { params: { path: { bot_id: bot.id } } }) : await api.POST('/api/bots/{bot_id}/config-backups/{backup_id}/restore', { params: { path: { bot_id: bot.id, backup_id: backupId! } } })
    if (!result.data) throw apiFailure(result.error, result.response)
    return result.data
  }, onSuccess: async (result, { operation }) => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['bots'] }), queryClient.invalidateQueries({ queryKey: ['bot'] }), queryClient.invalidateQueries({ queryKey: ['config-backups'] })]); showToast('Configuração atualizada.', 'success'); setImporting(false); if (operation === 'archive') navigate('/bots'); else if (operation === 'import') navigate(`/bots/${result.id}`) }, onError: (error) => showToast(errorMessage(error), 'error') })
  const target = targets.data?.find((item) => item.id === targetId && !item.is_test)
  if (!bot.is_test) return <section className="panel"><h2>Histórico de configuração</h2>{backups.isError && <p role="alert">{errorMessage(backups.error)}</p>}{!backups.data?.items.length && <p>Nenhum backup registrado.</p>}{backups.data?.items.map((backup) => <div key={backup.id}><span>{new Date(backup.created_at).toLocaleString('pt-BR')} · {backup.reason === 'restore' ? 'Restauração' : 'Importação de teste'} · {backup.source_bot_name ?? '—'}</span>{isAdmin && <ConfirmButton question={`Restaurar a configuração de ${bot.name}? A configuração atual será guardada em um novo backup.`} onConfirm={() => update.mutate({ operation: 'restore', backupId: backup.id })}>Restaurar</ConfirmButton>}</div>)}{backups.data && backups.data.total > 20 && <div className="page-actions"><button className="button ghost" disabled={backupPage === 1} onClick={() => setBackupPage(backupPage - 1)}>Anterior</button><span>Página {backupPage}</span><button className="button ghost" disabled={backupPage * 20 >= backups.data.total} onClick={() => setBackupPage(backupPage + 1)}>Próxima</button></div>}</section>
  return <section className="panel"><p>Bot de teste — os envios não contam no limite global do número. Os primeiros {bot.settings.content?.baseline_ciclos ?? 5} ciclos só registram as ofertas atuais sem enviar (baseline).</p>{isAdmin && !bot.archived_at && <div className="page-actions"><button className="button primary" onClick={() => { setConfirmed(false); setImporting(true) }}>Importar configuração para…</button><ConfirmButton question="Descartar este teste? Ele será arquivado e não executará mais." onConfirm={() => update.mutate({ operation: 'archive' })}>Descartar teste</ConfirmButton></div>}{importing && <Modal title="Importar configuração para…" size="wide" onClose={() => setImporting(false)}><Field label="Bot de destino"><select value={targetId} onChange={(event) => { setTargetId(event.target.value); setConfirmed(false) }}><option value="">Selecione um bot</option>{targets.data?.filter((item) => !item.is_test).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>{target && <><ConfigDifferences current={target} next={bot} /><label className="check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />Isso substitui a configuração de {target.name} e arquiva este bot de teste</label></>}<div className="form-actions"><button className="button ghost" onClick={() => setImporting(false)}>Cancelar</button><button className="button primary" disabled={!target || !confirmed || update.isPending} onClick={() => update.mutate({ operation: 'import' })}>Importar e arquivar</button></div></Modal>}</section>
}
